---
api_version: v1alpha1
groups:
  - name: node1
    spec: etcd1
    require:
      uuid: 16e7d8a7-bfa9-428b-9117-363341bb330b

  - name: node2
    spec: etcd2
    require:
      uuid: 264cd073-ca62-44b3-98c0-50aad5b5f819

  - name: node3
    spec: etcd3
    require:
      uuid: 39d2e747-2648-4d68-ae92-bbc70b245055

  - name: default
    spec: worker