language: go
sudo: false
go:
  - 1.5
  - tip
install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get -v -t ./...
script:
  - go test ./...
  - go vet ./...
  - golint ./...