language: go
sudo: required
services:
  - docker
go:
  - 1.5.3
  - 1.6
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT="1"
install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
script:
  - ./test
deploy:
  provider: script
  script: scripts/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.5.3'
    condition: "$TRAVIS_PULL_REQUEST = false"
notifications:
  email: false