language: go
sudo: required
services:
  - docker
go:
  - "1.10.x"
  - "1.11.x"
  - "1.11.7"
  - "1.12.x"
install:
  - go get golang.org/x/lint/golint
script:
  - make
deploy:
  provider: script
  script: scripts/dev/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.11.7'
notifications:
  email: change
