language: go
sudo: required
services:
  - docker
go:
  - 1.5
  - tip
install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get -v -t ./...
script:
  - go test ./...
  - go vet ./...
  - golint ./...
  - test -z "$(go fmt ./...)"
deploy:
  provider: script
  script: scripts/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.5'
    condition: "$TRAVIS_PULL_REQUEST = false"
notifications:
  email: false