language: go
sudo: required
services:
  - docker
go:
  - "1.11.x"
  - "1.12.x"
  - "1.12.10"
  - "1.13.x"
install:
  - go get golang.org/x/lint/golint
script:
  - make
deploy:
  - provider: script
    script: scripts/dev/travis-docker-push
    skip_cleanup: true
    on:
      branch: master
      go: '1.12.10'
  - provider: script
    script: contrib/dnsmasq/travis-deploy
    skip_cleanup: true
    on:
      branch: dnsmasq
      # pick one, so travis deploys once
      go: '1.11.x'
notifications:
  email: change
