language: go
sudo: required
services:
  - docker
go:
  - 1.10.x
  - 1.11.x
  - 1.11.1
  - tip
matrix:
  allow_failures:
    - go: tip
install:
  - go get golang.org/x/lint/golint
script:
  - make test
deploy:
  provider: script
  script: scripts/dev/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.11.1'
notifications:
  email: change
