language: go
sudo: required
services:
  - docker
go:
  - 1.5.4
  - 1.6.2
  - tip
matrix:
  allow_failures:
    - go: tip
env:
  global:
    - GO15VENDOREXPERIMENT="1"
install:
  - go get github.com/golang/lint/golint
script:
  - ./test
deploy:
  provider: script
  script: scripts/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.6.2'
    condition: "$TRAVIS_PULL_REQUEST = false"
notifications:
  email: false
