language: go
sudo: required
services:
  - docker
go:
  - 1.6.4
  - 1.7.4
  - tip
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/golang/lint/golint
script:
  - ./test
deploy:
  provider: script
  script: scripts/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.7.4'
    condition: "$TRAVIS_PULL_REQUEST = false"
notifications:
  email: change

