---
api_version: v1alpha1
groups:
  - name: node1
    spec: etcd1
    require:
      uuid: 16e7d8a7-bfa9-428b-9117-363341bb330b
    metadata:
      etcd_name: node1
      ipv4_local: 172.17.0.21
      etcd_initial_cluster: "node1=http://172.17.0.21:2380,node2=http://172.17.0.22:2380,node3=http://172.17.0.23:2380"

  - name: node2
    spec: etcd2
    require:
      uuid: 264cd073-ca62-44b3-98c0-50aad5b5f819
    metadata:
      etcd_name: node2
      ipv4_local: 172.17.0.22
      etcd_initial_cluster: "node1=http://172.17.0.21:2380,node2=http://172.17.0.22:2380,node3=http://172.17.0.23:2380"

  - name: node3
    spec: etcd3
    require:
      uuid: 39d2e747-2648-4d68-ae92-bbc70b245055
    metadata:
      etcd_name: node3
      ipv4_local: 172.17.0.23
      etcd_initial_cluster: "node1=http://172.17.0.21:2380,node2=http://172.17.0.22:2380,node3=http://172.17.0.23:2380"

  - name: default
    spec: etcd_proxy
    metadata:
      etcd_initial_cluster: "node1=http://172.17.0.21:2380,node2=http://172.17.0.22:2380,node3=http://172.17.0.23:2380"
